### ISSUE TITLE
ImportError: cannot import name 'patterns'

### ISSUE THREAD

**Issue by cs01** [tomchristie/rest-framework-tutorial#28]
As of Django 1.10, `patterns` does not exist. `tutorial/urls.py` attempts to import it, but it's no longer needed.

> Django loads that Python module and looks for the variable urlpatterns. This should be a Python list of django.conf.urls.url() instances.
https://docs.djangoproject.com/en/1.10/topics/http/urls/#how-django-processes-a-request

**Comment by tomchristie** [comment]
Good catch. Very happy to accept pull requests if you'd like to. Otherwise can look into resolving this myself. Either ways good by me.
