### ISSUE TITLE
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html

### ISSUE THREAD

**Issue by cs01** [tomchristie/rest-framework-tutorial#29]
`Django version 1.10.2, using settings 'tutorial.settings'`

>   File ".../site-packages/django/template/loader.py", line 25, in get_template
>     raise TemplateDoesNotExist(template_name, chain=chain)
> django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html

After running 
```
./manage migrate
./manage runserver
```

then attempting to view `http://127.0.0.1:8000/`, the above error is raised.

**Comment by tomchristie** [comment]
Have you omitted to include `rest_framework` in the `INSTALLED_APPS`?

**Comment by cs01** [comment]
No, it turned out I wasn't on the same version of Django/DRF. After setting up a new virtualenv and installing requirement.txt everything worked smoothly (same with issue 28 that I just opened). 

Is there a desire to keep this tutorial up to date with the latest Django/DRF? As someone who is just starting with DRF, I want to use the latest of all versions, but this code is not longer compatible with DRF 3.5.1/Django 1.10.2 (the latest as of today).

**Comment by tomchristie** [comment]
Yes, we oughta be keeping it up to date. Occasionally this repo drops out of date with the tutorial as we alter things. Now seems like one of those times.

**Comment by cs01** [comment]
Does that mean you are going to fix it? If not let me know and I'll give it a shot.

**Comment by tomchristie** [comment]
Unless you or someone else beats me to it, then yes.

**Comment by aixiamomo** [comment]
Add `'django_filters'` to `INSTALLED_APPS`
my version: Django == 1.11, django-rest-framework == 3.7.3

**Comment by sabuhish** [comment]
might be you have not added rest_framework to your installed apps or upgrde your django

**Comment by jonamadk** [comment]
Make sure you have rest_framework in your settings's INSTALLED_APPS
