### ISSUE TITLE
报错404

### ISSUE THREAD

**Issue by xuyafei9303** [tomchristie/rest-framework-tutorial#36]
您好，很抱歉我用的中文。
我根据你的教程写了代码，报错404， 然后下载您的代码发现跟教程的代码不一样？？

**Comment by tomchristie** [comment]
"Hello, sorry I am using Chinese.
I wrote the code according to your tutorial, error 404, and then download your code found with the tutorial code is not the same"

**Comment by tomchristie** [comment]
I would love to be able to help, but there's not enough information here for us to be able to know exactly what the problem is.

我很想能够帮助，但是这里没有足够的信息能够准确地知道问题。
